name: Selenium Tests with ExtentReports

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  selenium_tests:
    runs-on: windows-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Google Chrome (on Windows, we will use Chocolatey to install it)
      - name: Install Google Chrome
        run: |
          choco install googlechrome -y

      # Install ChromeDriver (on Windows, we use PowerShell commands to download and extract)
      - name: Install ChromeDriver
        run: |
          $CHROME_DRIVER_VERSION = (Invoke-RestMethod -Uri https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_win32.zip" -OutFile "chromedriver.zip"
          Expand-Archive -Path "chromedriver.zip" -DestinationPath "."
          Move-Item -Path "chromedriver.exe" -Destination "C:\Windows\System32\chromedriver.exe"
          
      # Run Selenium tests (using Maven in this example)
      - name: Run Selenium tests
        run: mvn test
